language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  global:
    - PYTHONPATH=src/
    - MYPYPATH=src/
install:
  - pip install -U poetry
  - poetry install
  - pip install -U coverage python-coveralls pytest-cov
script:
  - black src/ --check
  - mypy src/
  - pylint pymessagebus
  - pytest --cov pymessagebus --cov-report term-missing
after_success:
  - coveralls
